apiVersion: v1
kind: Secret
metadata:
  name: outline-keys
  namespace: zarf
  labels:
    generated-by: zarf
stringData:
  outline-secret-key: ###ZARF_VAR_OUTLINE_SECRET_KEY###
  outline-utils-secret: ###ZARF_VAR_OUTLINE_UTILS_SECRET###
