apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: outline
  namespace: {{ .Release.Namespace }}
spec:
  network:
    expose:
      - service: outline
        podLabels:
          app.kubernetes.io/name: outline
        gateway: tenant
        host: outline
        port: 80
        targetPort: 3000
    allow:
      # Todo: wide open for hitting in-cluster or external postgres/redis
      - direction: Egress
        podLabels:
          app.kubernetes.io/name: outline
        remoteGenerated: Anywhere
