apiVersion: apps/v1
kind: Deployment
metadata:
  name: outline
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: outline
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: outline
    spec:
      containers:
        - name: outline
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: outline-postgres
                  key: url
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: outline-redis
                  key: url
          ports:
            - containerPort: 3000
