apiVersion: v1
kind: Service
metadata:
  name: outline
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: outline
spec:
  ports:
    - port: 80
      targetPort: 3000
      name: http
  selector:
    app.kubernetes.io/name: outline
